### ISSUE TITLE
Rails example code not working on 1.4.1

### ISSUE THREAD

**Issue by janxious** [pandastream/panda_gem#4]
Thoughts?
    panda = Panda::Video.create(:source_url => "http://panda-test-harness-videos.s3.amazonaws.com/panda.mp4")
    panda.reload
    NameError: undefined local variable or method `cloud_id' for #<Panda::Video:0x1068f3fc0>
      from /Users/joel/projects/big_blue_wagon/vendor/bundle/ruby/1.8/gems/panda-1.4.1/lib/panda/base.rb:99:in`method_missing'
      from /Users/joel/projects/big_blue_wagon/vendor/bundle/ruby/1.8/gems/panda-1.4.1/lib/panda/resources/resource.rb:36:in `reload'
      from (irb):17
